module.exports = {
  apps: [
    {
      name: "onui-ai",
      script: "/home/scottk/Projects/onui-ai/scripts/run-uvicorn.sh",
      interpreter: "bash",
      cwd: "/home/scottk/Projects/onui-ai",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 8000,
      max_memory_restart: "1G",
      env_file: "/home/scottk/Projects/onui-ai/.env",
      error_file: "/home/scottk/Projects/onui-ai/logs/pm2-error.log",
      out_file: "/home/scottk/Projects/onui-ai/logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
    },
    {
      name: "onui-ai-ngrok",
      script: "/home/scottk/Projects/onui-ai/scripts/run-ngrok.sh",
      interpreter: "bash",
      cwd: "/home/scottk/Projects/onui-ai",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env_file: "/home/scottk/Projects/onui-ai/.env",
      error_file: "/home/scottk/Projects/onui-ai/logs/ngrok-pm2-error.log",
      out_file: "/home/scottk/Projects/onui-ai/logs/ngrok-pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
    },
  ],
};
